<?php
// This script and data application were generated by AppGini 5.70
// Download AppGini for free from https://bigprof.com/appgini/download/

	$currDir=dirname(__FILE__);
	include("$currDir/defaultLang.php");
	include("$currDir/language.php");
	include("$currDir/lib.php");
	@include("$currDir/hooks/staff.php");
	include("$currDir/staff_dml.php");

	// mm: can the current member access this page?
	$perm=getTablePermissions('staff');
	if(!$perm[0]){
		echo error_message($Translation['tableAccessDenied'], false);
		echo '<script>setTimeout("window.location=\'index.php?signOut=1\'", 2000);</script>';
		exit;
	}

	$x = new DataList;
	$x->TableName = "staff";

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = array(   
		"`staff`.`id`" => "id",
		"`staff`.`full_name`" => "full_name",
		"`staff`.`national_id`" => "national_id",
		"`staff`.`department`" => "department",
		"`staff`.`phone_number`" => "phone_number",
		"`staff`.`gender`" => "gender"
	);
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = array(   
		1 => '`staff`.`id`',
		2 => 2,
		3 => 3,
		4 => 4,
		5 => 5,
		6 => 6
	);

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = array(   
		"`staff`.`id`" => "id",
		"`staff`.`full_name`" => "full_name",
		"`staff`.`national_id`" => "national_id",
		"`staff`.`department`" => "department",
		"`staff`.`phone_number`" => "phone_number",
		"`staff`.`gender`" => "gender"
	);
	// Fields that can be filtered
	$x->QueryFieldsFilters = array(   
		"`staff`.`id`" => "id",
		"`staff`.`full_name`" => "FullName",
		"`staff`.`national_id`" => "National_ID",
		"`staff`.`department`" => "Department",
		"`staff`.`phone_number`" => "Phone_Number",
		"`staff`.`gender`" => "Gender"
	);

	// Fields that can be quick searched
	$x->QueryFieldsQS = array(   
		"`staff`.`id`" => "id",
		"`staff`.`full_name`" => "full_name",
		"`staff`.`national_id`" => "national_id",
		"`staff`.`department`" => "department",
		"`staff`.`phone_number`" => "phone_number",
		"`staff`.`gender`" => "gender"
	);

	// Lookup fields that can be used as filterers
	$x->filterers = array();

	$x->QueryFrom = "`staff` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 0;
	$x->HideTableView = ($perm[2]==0 ? 1 : 0);
	$x->AllowDelete = $perm[4];
	$x->AllowMassDelete = true;
	$x->AllowInsert = $perm[1];
	$x->AllowUpdate = $perm[3];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 1;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 50;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation["quick search"];
	$x->ScriptFileName = "staff_view.php";
	$x->RedirectAfterInsert = "staff_view.php";
	$x->TableTitle = "staff";
	$x->TableIcon = "resources/table_icons/angel.png";
	$x->PrimaryKey = "`staff`.`id`";

	$x->ColWidth   = array(  150, 150, 150, 150, 150, 150);
	$x->ColCaption = array("id", "FullName", "National_ID", "Department", "Phone_Number", "Gender");
	$x->ColFieldName = array('id', 'full_name', 'national_id', 'department', 'phone_number', 'gender');
	$x->ColNumber  = array(1, 2, 3, 4, 5, 6);

	// template paths below are based on the app main directory
	$x->Template = 'templates/staff_templateTV.html';
	$x->SelectedTemplate = 'templates/staff_templateTVS.html';
	$x->TemplateDV = 'templates/staff_templateDV.html';
	$x->TemplateDVP = 'templates/staff_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->ShowRecordSlots = 0;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HighlightColor = '#FFF0C2';

	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, array('user', 'group'))){ $DisplayRecords = 'all'; }
	if($perm[2]==1 || ($perm[2]>1 && $DisplayRecords=='user' && !$_REQUEST['NoFilter_x'])){ // view owner only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `staff`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='staff' and lcase(membership_userrecords.memberID)='".getLoggedMemberID()."'";
	}elseif($perm[2]==2 || ($perm[2]>2 && $DisplayRecords=='group' && !$_REQUEST['NoFilter_x'])){ // view group only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `staff`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='staff' and membership_userrecords.groupID='".getLoggedGroupID()."'";
	}elseif($perm[2]==3){ // view all
		// no further action
	}elseif($perm[2]==0){ // view none
		$x->QueryFields = array("Not enough permissions" => "NEP");
		$x->QueryFrom = '`staff`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
	// hook: staff_init
	$render=TRUE;
	if(function_exists('staff_init')){
		$args=array();
		$render=staff_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: staff_header
	$headerCode='';
	if(function_exists('staff_header')){
		$args=array();
		$headerCode=staff_header($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$headerCode){
		include_once("$currDir/header.php"); 
	}else{
		ob_start(); include_once("$currDir/header.php"); $dHeader=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%HEADER%%>', $dHeader, $headerCode);
	}

	echo $x->HTML;
	// hook: staff_footer
	$footerCode='';
	if(function_exists('staff_footer')){
		$args=array();
		$footerCode=staff_footer($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$footerCode){
		include_once("$currDir/footer.php"); 
	}else{
		ob_start(); include_once("$currDir/footer.php"); $dFooter=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%FOOTER%%>', $dFooter, $footerCode);
	}
?>